import jsPDF from "jspdf";

export const downloadReport = ({ score, suggestions, formData }) => {
  const doc = new jsPDF();
  let y = 20;
  const margin = 14;
  const maxWidth = 180;

  // Helper to check if a new page is needed to prevent text from overflowing
  const checkPageBreak = (heightNeeded) => {
    if (y + heightNeeded > 280) {
      doc.addPage();
      y = 20;
    }
  };

  // Title
  doc.setFontSize(22);
  doc.setTextColor(15, 82, 186); // Brand blue matching UI
  doc.setFont("helvetica", "bold");
  doc.text("UrBridge.ai - Resume Analysis Report", margin, y);
  y += 5;

  // Separator
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, 210 - margin, y);
  y += 10;

  // Score Section
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "bold");
  doc.text(`Profile Readiness Score: ${score !== null ? score : "N/A"}/100`, margin, y);
  y += 10;

  if (formData) {
    // Profile Details
    doc.setFontSize(14);
    doc.setTextColor(15, 82, 186);
    doc.setFont("helvetica", "bold");
    doc.text("Profile Details", margin, y);
    y += 7;

    doc.setFontSize(11);
    doc.setTextColor(50, 50, 50);
    doc.setFont("helvetica", "normal");

    const details = [
      formData.desiredJobRoles && `Desired Role: ${formData.desiredJobRoles}`,
      formData.experience && `Experience: ${formData.experience} years`,
      formData.education && `Education: ${formData.education === "Other" ? formData.customEducation : formData.education}`,
      formData.currentCity && `City: ${formData.currentCity}`,
      formData.previousJobTitle && `Previous Title: ${formData.previousJobTitle}`,
    ].filter(Boolean);

    details.forEach((detail) => {
      checkPageBreak(6);
      doc.text(`•  ${detail}`, margin + 4, y);
      y += 6;
    });
    y += 4;

    // Skills (Comma separated to save vertical space)
    if (formData.skills && formData.skills.length > 0 && formData.skills.some((s) => s.trim())) {
      checkPageBreak(15);
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0, 0, 0);
      doc.text("Skills:", margin + 4, y);
      
      doc.setFont("helvetica", "normal");
      doc.setTextColor(50, 50, 50);
      const skillsText = formData.skills.filter((s) => s.trim()).join(", ");
      const splitSkills = doc.splitTextToSize(skillsText, maxWidth - 4);
      y += 6;
      doc.text(splitSkills, margin + 4, y);
      y += splitSkills.length * 6 + 2;
    }

    // Certifications
    if (formData.certifications && formData.certifications.length > 0 && formData.certifications.some((c) => c.trim())) {
      checkPageBreak(15);
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0, 0, 0);
      doc.text("Certifications:", margin + 4, y);
      y += 6;

      doc.setFont("helvetica", "normal");
      doc.setTextColor(50, 50, 50);
      formData.certifications.forEach((cert) => {
        if (cert.trim()) {
          const splitCert = doc.splitTextToSize(`- ${cert.trim()}`, maxWidth - 8);
          checkPageBreak(splitCert.length * 6);
          doc.text(splitCert, margin + 8, y);
          y += splitCert.length * 6;
        }
      });
      y += 4;
    }
  }

  // Suggestions Section
  checkPageBreak(15);
  doc.setFontSize(14);
  doc.setTextColor(15, 82, 186);
  doc.setFont("helvetica", "bold");
  doc.text("Actionable Suggestions", margin, y);
  y += 7;

  doc.setFontSize(11);
  doc.setTextColor(50, 50, 50);
  doc.setFont("helvetica", "normal");

  if (!suggestions || suggestions.length === 0) {
    doc.text("•  No suggestions available at this moment.", margin + 4, y);
  } else {
    suggestions.forEach((suggestion) => {
      // Dynamically wrap text so it fits the PDF width
      const splitSuggestion = doc.splitTextToSize(`•  ${suggestion}`, maxWidth);
      checkPageBreak(splitSuggestion.length * 6);
      doc.text(splitSuggestion, margin + 4, y);
      y += splitSuggestion.length * 6 + 2;
    });
  }

  // Footer (Added to the bottom of the final page)
  const pageHeight = doc.internal.pageSize.height || doc.internal.pageSize.getHeight();
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by UrBridge.ai", margin, pageHeight - 10);

  doc.save("UrBridge_Resume_Report.pdf");
};