const TRENDING_SKILLS = {
  "data scientist": [
    { skill: "machine learning", trend: 98 },
    { skill: "python", trend: 96 },
    { skill: "deep learning", trend: 92 },
    { skill: "sql", trend: 90 },
    { skill: "data visualization", trend: 85 },
    { skill: "pandas", trend: 82 },
    { skill: "feature engineering", trend: 78 },
    { skill: "numpy", trend: 74 },
    { skill: "scikit-learn", trend: 70 },
    { skill: "statistics", trend: 65 },
    { skill: "tableau", trend: 55 },
    { skill: "model evaluation", trend: 50 },
  ],
  "data analyst": [
    { skill: "sql", trend: 98 },
    { skill: "power bi", trend: 92 },
    { skill: "excel", trend: 88 },
    { skill: "python", trend: 85 },
    { skill: "tableau", trend: 80 },
    { skill: "data visualization", trend: 78 },
    { skill: "data cleaning", trend: 70 },
    { skill: "statistics", trend: 65 },
    { skill: "reporting", trend: 55 },
    { skill: "dashboards", trend: 50 },
  ],
  "machine learning engineer": [
    { skill: "python", trend: 98 },
    { skill: "deep learning", trend: 95 },
    { skill: "tensorflow", trend: 92 },
    { skill: "pytorch", trend: 90 },
    { skill: "mlops", trend: 88 },
    { skill: "docker", trend: 82 },
    { skill: "model deployment", trend: 80 },
    { skill: "scikit-learn", trend: 75 },
    { skill: "aws", trend: 70 },
    { skill: "feature engineering", trend: 65 },
    { skill: "sql", trend: 58 },
    { skill: "api development", trend: 52 },
  ],
  "ai/ml engineer": [
    { skill: "machine learning", trend: 98 },
    { skill: "deep learning", trend: 96 },
    { skill: "python", trend: 94 },
    { skill: "neural networks", trend: 92 },
    { skill: "nlp", trend: 90 },
    { skill: "computer vision", trend: 88 },
    { skill: "tensorflow", trend: 85 },
    { skill: "pytorch", trend: 82 },
    { skill: "transformers", trend: 80 },
    { skill: "mlops", trend: 75 },
    { skill: "model optimization", trend: 70 },
    { skill: "reinforcement learning", trend: 65 },
    { skill: "generative ai", trend: 60 },
  ],
  "ai engineer": [
    { skill: "machine learning", trend: 98 },
    { skill: "deep learning", trend: 96 },
    { skill: "python", trend: 94 },
    { skill: "neural networks", trend: 92 },
    { skill: "nlp", trend: 90 },
    { skill: "computer vision", trend: 88 },
    { skill: "tensorflow", trend: 85 },
    { skill: "pytorch", trend: 82 },
    { skill: "transformers", trend: 80 },
    { skill: "mlops", trend: 75 },
    { skill: "model optimization", trend: 70 },
    { skill: "reinforcement learning", trend: 65 },
    { skill: "generative ai", trend: 60 },
  ],
  "ml engineer": [
    { skill: "python", trend: 98 },
    { skill: "deep learning", trend: 95 },
    { skill: "tensorflow", trend: 92 },
    { skill: "pytorch", trend: 90 },
    { skill: "mlops", trend: 88 },
    { skill: "docker", trend: 82 },
    { skill: "model deployment", trend: 80 },
    { skill: "scikit-learn", trend: 75 },
    { skill: "aws", trend: 70 },
    { skill: "feature engineering", trend: 65 },
    { skill: "sql", trend: 58 },
    { skill: "api development", trend: 52 },
  ],
  "backend developer": [
    { skill: "node.js", trend: 96 },
    { skill: "api development", trend: 94 },
    { skill: "docker", trend: 90 },
    { skill: "postgresql", trend: 86 },
    { skill: "mongodb", trend: 82 },
    { skill: "system design", trend: 80 },
    { skill: "redis", trend: 75 },
    { skill: "authentication", trend: 70 },
    { skill: "graphql", trend: 65 },
    { skill: "microservices", trend: 62 },
    { skill: "sql", trend: 58 },
    { skill: "express", trend: 52 },
  ],
  "frontend developer": [
    { skill: "react", trend: 98 },
    { skill: "typescript", trend: 94 },
    { skill: "next.js", trend: 90 },
    { skill: "javascript", trend: 88 },
    { skill: "tailwind css", trend: 85 },
    { skill: "state management", trend: 78 },
    { skill: "vite", trend: 72 },
    { skill: "responsive design", trend: 68 },
    { skill: "redux", trend: 60 },
    { skill: "accessibility", trend: 55 },
    { skill: "html", trend: 50 },
    { skill: "css", trend: 48 },
  ],
  "full stack developer": [
    { skill: "react", trend: 96 },
    { skill: "node.js", trend: 94 },
    { skill: "typescript", trend: 90 },
    { skill: "docker", trend: 86 },
    { skill: "mongodb", trend: 80 },
    { skill: "api development", trend: 78 },
    { skill: "next.js", trend: 74 },
    { skill: "postgresql", trend: 68 },
    { skill: "authentication", trend: 62 },
    { skill: "git", trend: 58 },
    { skill: "html", trend: 50 },
    { skill: "css", trend: 46 },
  ],
  "software engineer": [
    { skill: "data structures", trend: 96 },
    { skill: "algorithms", trend: 94 },
    { skill: "system design", trend: 90 },
    { skill: "problem solving", trend: 86 },
    { skill: "api development", trend: 80 },
    { skill: "git", trend: 75 },
    { skill: "testing", trend: 68 },
    { skill: "debugging", trend: 62 },
    { skill: "sql", trend: 58 },
    { skill: "object oriented programming", trend: 54 },
  ],
  "devops engineer": [
    { skill: "kubernetes", trend: 96 },
    { skill: "docker", trend: 94 },
    { skill: "ci/cd", trend: 92 },
    { skill: "terraform", trend: 88 },
    { skill: "aws", trend: 85 },
    { skill: "github actions", trend: 80 },
    { skill: "linux", trend: 75 },
    { skill: "monitoring", trend: 68 },
    { skill: "ansible", trend: 60 },
    { skill: "shell scripting", trend: 55 },
    { skill: "networking", trend: 48 },
  ],
  "ui/ux designer": [
    { skill: "figma", trend: 98 },
    { skill: "user research", trend: 94 },
    { skill: "wireframing", trend: 90 },
    { skill: "prototyping", trend: 88 },
    { skill: "design systems", trend: 85 },
    { skill: "usability testing", trend: 80 },
    { skill: "adobe xd", trend: 72 },
    { skill: "interaction design", trend: 68 },
    { skill: "accessibility", trend: 64 },
    { skill: "html", trend: 55 },
    { skill: "css", trend: 52 },
    { skill: "photoshop", trend: 45 },
  ],
  "android developer": [
    { skill: "kotlin", trend: 98 },
    { skill: "jetpack compose", trend: 94 },
    { skill: "android sdk", trend: 90 },
    { skill: "mvvm", trend: 86 },
    { skill: "retrofit", trend: 80 },
    { skill: "coroutines", trend: 78 },
    { skill: "room database", trend: 72 },
    { skill: "firebase", trend: 68 },
    { skill: "java", trend: 60 },
    { skill: "git", trend: 55 },
    { skill: "api development", trend: 50 },
    { skill: "unit testing", trend: 45 },
  ],
  "ios developer": [
    { skill: "swift", trend: 98 },
    { skill: "swiftui", trend: 95 },
    { skill: "xcode", trend: 90 },
    { skill: "uikit", trend: 85 },
    { skill: "combine", trend: 80 },
    { skill: "core data", trend: 74 },
    { skill: "mvvm", trend: 70 },
    { skill: "firebase", trend: 65 },
    { skill: "rest api", trend: 60 },
    { skill: "git", trend: 55 },
    { skill: "unit testing", trend: 50 },
    { skill: "objective-c", trend: 35 },
  ],
  "cybersecurity engineer": [
    { skill: "penetration testing", trend: 98 },
    { skill: "network security", trend: 95 },
    { skill: "siem", trend: 90 },
    { skill: "vulnerability assessment", trend: 88 },
    { skill: "python", trend: 84 },
    { skill: "incident response", trend: 80 },
    { skill: "linux", trend: 76 },
    { skill: "firewalls", trend: 70 },
    { skill: "cryptography", trend: 65 },
    { skill: "ethical hacking", trend: 62 },
    { skill: "cloud security", trend: 58 },
    { skill: "compliance", trend: 50 },
  ],
  "cloud engineer": [
    { skill: "aws", trend: 98 },
    { skill: "azure", trend: 94 },
    { skill: "gcp", trend: 90 },
    { skill: "terraform", trend: 88 },
    { skill: "kubernetes", trend: 85 },
    { skill: "docker", trend: 82 },
    { skill: "ci/cd", trend: 78 },
    { skill: "networking", trend: 72 },
    { skill: "linux", trend: 68 },
    { skill: "python", trend: 62 },
    { skill: "monitoring", trend: 58 },
    { skill: "shell scripting", trend: 50 },
  ],
  "product manager": [
    { skill: "product roadmap", trend: 98 },
    { skill: "agile", trend: 95 },
    { skill: "user research", trend: 90 },
    { skill: "data analysis", trend: 86 },
    { skill: "stakeholder management", trend: 82 },
    { skill: "jira", trend: 78 },
    { skill: "scrum", trend: 74 },
    { skill: "a/b testing", trend: 68 },
    { skill: "sql", trend: 62 },
    { skill: "figma", trend: 58 },
    { skill: "communication", trend: 54 },
    { skill: "documentation", trend: 48 },
  ],
  "business analyst": [
    { skill: "sql", trend: 96 },
    { skill: "data analysis", trend: 94 },
    { skill: "excel", trend: 90 },
    { skill: "power bi", trend: 86 },
    { skill: "requirements gathering", trend: 82 },
    { skill: "stakeholder management", trend: 78 },
    { skill: "process mapping", trend: 72 },
    { skill: "agile", trend: 68 },
    { skill: "tableau", trend: 62 },
    { skill: "documentation", trend: 58 },
    { skill: "communication", trend: 54 },
    { skill: "jira", trend: 48 },
  ],
  "python developer": [
    { skill: "python", trend: 98 },
    { skill: "django", trend: 92 },
    { skill: "flask", trend: 88 },
    { skill: "fastapi", trend: 85 },
    { skill: "sql", trend: 80 },
    { skill: "api development", trend: 78 },
    { skill: "docker", trend: 74 },
    { skill: "git", trend: 70 },
    { skill: "postgresql", trend: 65 },
    { skill: "redis", trend: 60 },
    { skill: "testing", trend: 55 },
    { skill: "aws", trend: 50 },
  ],
  "java developer": [
    { skill: "java", trend: 98 },
    { skill: "spring boot", trend: 94 },
    { skill: "microservices", trend: 90 },
    { skill: "sql", trend: 86 },
    { skill: "hibernate", trend: 82 },
    { skill: "docker", trend: 78 },
    { skill: "kubernetes", trend: 74 },
    { skill: "maven", trend: 68 },
    { skill: "git", trend: 64 },
    { skill: "rest api", trend: 60 },
    { skill: "junit", trend: 55 },
    { skill: "aws", trend: 50 },
  ],
  "web developer": [
    { skill: "html", trend: 98 },
    { skill: "css", trend: 96 },
    { skill: "javascript", trend: 94 },
    { skill: "react", trend: 90 },
    { skill: "node.js", trend: 86 },
    { skill: "responsive design", trend: 82 },
    { skill: "git", trend: 78 },
    { skill: "tailwind css", trend: 74 },
    { skill: "typescript", trend: 70 },
    { skill: "api development", trend: 65 },
    { skill: "mongodb", trend: 60 },
    { skill: "sql", trend: 55 },
  ],
  "game developer": [
    { skill: "unity", trend: 98 },
    { skill: "c#", trend: 95 },
    { skill: "unreal engine", trend: 92 },
    { skill: "c++", trend: 88 },
    { skill: "3d modeling", trend: 84 },
    { skill: "physics simulation", trend: 80 },
    { skill: "game design", trend: 76 },
    { skill: "animation", trend: 70 },
    { skill: "shader programming", trend: 65 },
    { skill: "multiplayer networking", trend: 60 },
    { skill: "ai programming", trend: 55 },
    { skill: "optimization", trend: 50 },
  ],
  "database administrator": [
    { skill: "sql", trend: 98 },
    { skill: "mysql", trend: 94 },
    { skill: "postgresql", trend: 90 },
    { skill: "database optimization", trend: 88 },
    { skill: "mongodb", trend: 84 },
    { skill: "backup and recovery", trend: 80 },
    { skill: "data modeling", trend: 76 },
    { skill: "performance tuning", trend: 72 },
    { skill: "oracle", trend: 68 },
    { skill: "nosql", trend: 64 },
    { skill: "cloud databases", trend: 60 },
    { skill: "data security", trend: 55 },
  ],
  "qa engineer": [
    { skill: "selenium", trend: 96 },
    { skill: "test automation", trend: 94 },
    { skill: "api testing", trend: 90 },
    { skill: "manual testing", trend: 86 },
    { skill: "jira", trend: 82 },
    { skill: "postman", trend: 78 },
    { skill: "cypress", trend: 74 },
    { skill: "performance testing", trend: 70 },
    { skill: "ci/cd", trend: 66 },
    { skill: "sql", trend: 62 },
    { skill: "agile", trend: 58 },
    { skill: "bug tracking", trend: 54 },
  ],
  "blockchain developer": [
    { skill: "solidity", trend: 98 },
    { skill: "ethereum", trend: 95 },
    { skill: "smart contracts", trend: 92 },
    { skill: "web3.js", trend: 88 },
    { skill: "defi", trend: 85 },
    { skill: "cryptography", trend: 80 },
    { skill: "nft", trend: 75 },
    { skill: "rust", trend: 70 },
    { skill: "javascript", trend: 65 },
    { skill: "node.js", trend: 60 },
    { skill: "ipfs", trend: 55 },
    { skill: "consensus algorithms", trend: 50 },
  ],
  "technical writer": [
    { skill: "technical documentation", trend: 98 },
    { skill: "markdown", trend: 94 },
    { skill: "api documentation", trend: 90 },
    { skill: "content management", trend: 86 },
    { skill: "git", trend: 82 },
    { skill: "seo", trend: 78 },
    { skill: "editing", trend: 74 },
    { skill: "research", trend: 70 },
    { skill: "communication", trend: 66 },
    { skill: "diagrams", trend: 62 },
    { skill: "version control", trend: 58 },
    { skill: "agile", trend: 54 },
  ],
  "marketing manager": [
    { skill: "digital marketing", trend: 98 },
    { skill: "seo", trend: 95 },
    { skill: "content marketing", trend: 92 },
    { skill: "google analytics", trend: 90 },
    { skill: "social media marketing", trend: 88 },
    { skill: "email marketing", trend: 85 },
    { skill: "sem", trend: 82 },
    { skill: "brand strategy", trend: 78 },
    { skill: "marketing automation", trend: 75 },
    { skill: "copywriting", trend: 70 },
    { skill: "data analysis", trend: 65 },
    { skill: "crm", trend: 60 },
  ],
  "sales manager": [
    { skill: "crm", trend: 98 },
    { skill: "salesforce", trend: 95 },
    { skill: "lead generation", trend: 92 },
    { skill: "negotiation", trend: 90 },
    { skill: "pipeline management", trend: 88 },
    { skill: "b2b sales", trend: 85 },
    { skill: "account management", trend: 82 },
    { skill: "sales strategy", trend: 78 },
    { skill: "communication", trend: 75 },
    { skill: "data analysis", trend: 70 },
    { skill: "presentation skills", trend: 65 },
    { skill: "cold calling", trend: 60 },
  ],
  "human resources manager": [
    { skill: "recruitment", trend: 98 },
    { skill: "employee relations", trend: 95 },
    { skill: "hr policies", trend: 92 },
    { skill: "talent management", trend: 90 },
    { skill: "payroll management", trend: 88 },
    { skill: "performance management", trend: 85 },
    { skill: "labor law", trend: 82 },
    { skill: "training and development", trend: 78 },
    { skill: "hris", trend: 75 },
    { skill: "compensation planning", trend: 70 },
    { skill: "conflict resolution", trend: 65 },
    { skill: "onboarding", trend: 60 },
  ],
  "financial analyst": [
    { skill: "financial modeling", trend: 98 },
    { skill: "excel", trend: 96 },
    { skill: "data analysis", trend: 94 },
    { skill: "sql", trend: 90 },
    { skill: "forecasting", trend: 88 },
    { skill: "valuation", trend: 85 },
    { skill: "risk analysis", trend: 82 },
    { skill: "financial reporting", trend: 78 },
    { skill: "power bi", trend: 75 },
    { skill: "bloomberg terminal", trend: 70 },
    { skill: "accounting", trend: 65 },
    { skill: "python", trend: 60 },
  ],
  "accountant": [
    { skill: "accounting", trend: 98 },
    { skill: "quickbooks", trend: 95 },
    { skill: "tax preparation", trend: 92 },
    { skill: "financial reporting", trend: 90 },
    { skill: "excel", trend: 88 },
    { skill: "audit", trend: 85 },
    { skill: "bookkeeping", trend: 82 },
    { skill: "gaap", trend: 78 },
    { skill: "payroll", trend: 75 },
    { skill: "sap", trend: 70 },
    { skill: "budgeting", trend: 65 },
    { skill: "tax compliance", trend: 60 },
  ],
  "project manager": [
    { skill: "project planning", trend: 98 },
    { skill: "agile", trend: 96 },
    { skill: "scrum", trend: 94 },
    { skill: "risk management", trend: 90 },
    { skill: "stakeholder management", trend: 88 },
    { skill: "jira", trend: 85 },
    { skill: "budgeting", trend: 82 },
    { skill: "ms project", trend: 78 },
    { skill: "communication", trend: 75 },
    { skill: "leadership", trend: 70 },
    { skill: "problem solving", trend: 65 },
    { skill: "time management", trend: 60 },
  ],
  "graphic designer": [
    { skill: "adobe photoshop", trend: 98 },
    { skill: "adobe illustrator", trend: 96 },
    { skill: "figma", trend: 94 },
    { skill: "adobe indesign", trend: 90 },
    { skill: "branding", trend: 88 },
    { skill: "typography", trend: 85 },
    { skill: "ui design", trend: 82 },
    { skill: "print design", trend: 78 },
    { skill: "motion graphics", trend: 75 },
    { skill: "after effects", trend: 70 },
    { skill: "creative direction", trend: 65 },
    { skill: "adobe xd", trend: 60 },
  ],
  "content writer": [
    { skill: "content writing", trend: 98 },
    { skill: "seo", trend: 95 },
    { skill: "copywriting", trend: 92 },
    { skill: "blogging", trend: 90 },
    { skill: "editing", trend: 88 },
    { skill: "research", trend: 85 },
    { skill: "wordpress", trend: 82 },
    { skill: "social media", trend: 78 },
    { skill: "storytelling", trend: 75 },
    { skill: "grammar", trend: 70 },
    { skill: "content strategy", trend: 65 },
    { skill: "proofreading", trend: 60 },
  ],
  "civil engineer": [
    { skill: "autocad", trend: 98 },
    { skill: "structural analysis", trend: 95 },
    { skill: "project management", trend: 92 },
    { skill: "construction management", trend: 90 },
    { skill: "site planning", trend: 88 },
    { skill: "revit", trend: 85 },
    { skill: "civil 3d", trend: 82 },
    { skill: "building codes", trend: 78 },
    { skill: "cost estimation", trend: 75 },
    { skill: "geotechnical engineering", trend: 70 },
    { skill: "surveying", trend: 65 },
    { skill: "environmental engineering", trend: 60 },
  ],
  "mechanical engineer": [
    { skill: "cad", trend: 98 },
    { skill: "solidworks", trend: 95 },
    { skill: "autocad", trend: 92 },
    { skill: "thermodynamics", trend: 90 },
    { skill: "finite element analysis", trend: 88 },
    { skill: "matlab", trend: 85 },
    { skill: "manufacturing processes", trend: 82 },
    { skill: "mechanical design", trend: 78 },
    { skill: "hvac", trend: 75 },
    { skill: "fluid mechanics", trend: 70 },
    { skill: "quality control", trend: 65 },
    { skill: "project management", trend: 60 },
  ],
  "electrical engineer": [
    { skill: "circuit design", trend: 98 },
    { skill: "pcb design", trend: 95 },
    { skill: "matlab", trend: 92 },
    { skill: "power systems", trend: 90 },
    { skill: "microcontrollers", trend: 88 },
    { skill: "autocad electrical", trend: 85 },
    { skill: "plc programming", trend: 82 },
    { skill: "signal processing", trend: 78 },
    { skill: "control systems", trend: 75 },
    { skill: "testing", trend: 70 },
    { skill: "embedded systems", trend: 65 },
    { skill: "renewable energy", trend: 60 },
  ],
  "nurse": [
    { skill: "patient care", trend: 98 },
    { skill: "medication administration", trend: 95 },
    { skill: "vital signs monitoring", trend: 92 },
    { skill: "emr", trend: 90 },
    { skill: "clinical documentation", trend: 88 },
    { skill: "wound care", trend: 85 },
    { skill: "iv therapy", trend: 82 },
    { skill: "patient education", trend: 78 },
    { skill: "emergency response", trend: 75 },
    { skill: "infection control", trend: 70 },
    { skill: "communication", trend: 65 },
    { skill: "critical thinking", trend: 60 },
  ],
  "doctor": [
    { skill: "diagnosis", trend: 98 },
    { skill: "patient care", trend: 96 },
    { skill: "clinical research", trend: 94 },
    { skill: "medical terminology", trend: 92 },
    { skill: "emr", trend: 90 },
    { skill: "treatment planning", trend: 88 },
    { skill: "surgery", trend: 85 },
    { skill: "pharmacology", trend: 82 },
    { skill: "emergency medicine", trend: 78 },
    { skill: "patient communication", trend: 75 },
    { skill: "medical imaging", trend: 70 },
    { skill: "evidence-based medicine", trend: 65 },
  ],
  "teacher": [
    { skill: "curriculum development", trend: 98 },
    { skill: "classroom management", trend: 96 },
    { skill: "lesson planning", trend: 94 },
    { skill: "student assessment", trend: 90 },
    { skill: "educational technology", trend: 88 },
    { skill: "differentiated instruction", trend: 85 },
    { skill: "communication", trend: 82 },
    { skill: "special education", trend: 78 },
    { skill: "google classroom", trend: 75 },
    { skill: "parent communication", trend: 70 },
    { skill: "behavior management", trend: 65 },
    { skill: "data-driven instruction", trend: 60 },
  ],
  "chef": [
    { skill: "culinary arts", trend: 98 },
    { skill: "food safety", trend: 96 },
    { skill: "menu planning", trend: 94 },
    { skill: "recipe development", trend: 90 },
    { skill: "kitchen management", trend: 88 },
    { skill: "food preparation", trend: 85 },
    { skill: "inventory management", trend: 82 },
    { skill: "plating", trend: 78 },
    { skill: "baking", trend: 75 },
    { skill: "cost control", trend: 70 },
    { skill: "nutrition", trend: 65 },
    { skill: "team leadership", trend: 60 },
  ],
  "hotel manager": [
    { skill: "hospitality management", trend: 98 },
    { skill: "customer service", trend: 96 },
    { skill: "revenue management", trend: 94 },
    { skill: "staff supervision", trend: 90 },
    { skill: "budgeting", trend: 88 },
    { skill: "operations management", trend: 85 },
    { skill: "event planning", trend: 82 },
    { skill: "property management systems", trend: 78 },
    { skill: "quality assurance", trend: 75 },
    { skill: "conflict resolution", trend: 70 },
    { skill: "marketing", trend: 65 },
    { skill: "guest relations", trend: 60 },
  ],
  "supply chain manager": [
    { skill: "supply chain management", trend: 98 },
    { skill: "logistics", trend: 96 },
    { skill: "inventory management", trend: 94 },
    { skill: "procurement", trend: 90 },
    { skill: "erp systems", trend: 88 },
    { skill: "data analysis", trend: 85 },
    { skill: "vendor management", trend: 82 },
    { skill: "demand forecasting", trend: 78 },
    { skill: "warehouse management", trend: 75 },
    { skill: "excel", trend: 70 },
    { skill: "lean six sigma", trend: 65 },
    { skill: "risk management", trend: 60 },
  ],
  "operations manager": [
    { skill: "operations management", trend: 98 },
    { skill: "process improvement", trend: 96 },
    { skill: "lean manufacturing", trend: 94 },
    { skill: "project management", trend: 90 },
    { skill: "budgeting", trend: 88 },
    { skill: "team leadership", trend: 85 },
    { skill: "kpi tracking", trend: 82 },
    { skill: "quality management", trend: 78 },
    { skill: "six sigma", trend: 75 },
    { skill: "data analysis", trend: 70 },
    { skill: "strategic planning", trend: 65 },
    { skill: "supply chain", trend: 60 },
  ],
  "legal advisor": [
    { skill: "legal research", trend: 98 },
    { skill: "contract drafting", trend: 96 },
    { skill: "legal writing", trend: 94 },
    { skill: "litigation", trend: 90 },
    { skill: "case management", trend: 88 },
    { skill: "compliance", trend: 85 },
    { skill: "negotiation", trend: 82 },
    { skill: "corporate law", trend: 78 },
    { skill: "intellectual property", trend: 75 },
    { skill: "client counseling", trend: 70 },
    { skill: "legal analysis", trend: 65 },
    { skill: "document review", trend: 60 },
  ],
  "architect": [
    { skill: "autocad", trend: 98 },
    { skill: "revit", trend: 96 },
    { skill: "sketchup", trend: 94 },
    { skill: "architectural design", trend: 90 },
    { skill: "3d modeling", trend: 88 },
    { skill: "building codes", trend: 85 },
    { skill: "sustainable design", trend: 82 },
    { skill: "construction documents", trend: 78 },
    { skill: "interior design", trend: 75 },
    { skill: "project management", trend: 70 },
    { skill: "bim", trend: 65 },
    { skill: "rhino", trend: 60 },
  ],
  "pharmacist": [
    { skill: "pharmacology", trend: 98 },
    { skill: "medication dispensing", trend: 96 },
    { skill: "patient counseling", trend: 94 },
    { skill: "drug interactions", trend: 90 },
    { skill: "pharmacy management", trend: 88 },
    { skill: "prescription processing", trend: 85 },
    { skill: "clinical pharmacy", trend: 82 },
    { skill: "inventory management", trend: 78 },
    { skill: "compounding", trend: 75 },
    { skill: "healthcare regulations", trend: 70 },
    { skill: "immunization", trend: 65 },
    { skill: "electronic health records", trend: 60 },
  ],
  "data engineer": [
    { skill: "python", trend: 98 },
    { skill: "sql", trend: 96 },
    { skill: "apache spark", trend: 94 },
    { skill: "aws", trend: 90 },
    { skill: "etl", trend: 88 },
    { skill: "hadoop", trend: 85 },
    { skill: "data warehousing", trend: 82 },
    { skill: "airflow", trend: 78 },
    { skill: "kafka", trend: 75 },
    { skill: "scala", trend: 70 },
    { skill: "snowflake", trend: 65 },
    { skill: "dbt", trend: 60 },
  ],
  "systems administrator": [
    { skill: "linux", trend: 98 },
    { skill: "windows server", trend: 96 },
    { skill: "networking", trend: 94 },
    { skill: "active directory", trend: 90 },
    { skill: "vmware", trend: 88 },
    { skill: "scripting", trend: 85 },
    { skill: "dns", trend: 82 },
    { skill: "firewall management", trend: 78 },
    { skill: "backup and recovery", trend: 75 },
    { skill: "monitoring", trend: 70 },
    { skill: "cloud infrastructure", trend: 65 },
    { skill: "troubleshooting", trend: 60 },
  ],
  "network engineer": [
    { skill: "cisco", trend: 98 },
    { skill: "routing", trend: 96 },
    { skill: "switching", trend: 94 },
    { skill: "tcp/ip", trend: 90 },
    { skill: "network security", trend: 88 },
    { skill: "firewall configuration", trend: 85 },
    { skill: "vpn", trend: 82 },
    { skill: "wireless networking", trend: 78 },
    { skill: "subnetting", trend: 75 },
    { skill: "mpls", trend: 70 },
    { skill: "sdn", trend: 65 },
    { skill: "network monitoring", trend: 60 },
  ],
  "digital marketing specialist": [
    { skill: "google ads", trend: 98 },
    { skill: "facebook ads", trend: 96 },
    { skill: "seo", trend: 94 },
    { skill: "google analytics", trend: 90 },
    { skill: "content marketing", trend: 88 },
    { skill: "email marketing", trend: 85 },
    { skill: "social media", trend: 82 },
    { skill: "copywriting", trend: 78 },
    { skill: "marketing automation", trend: 75 },
    { skill: "a/b testing", trend: 70 },
    { skill: "sem", trend: 65 },
    { skill: "influencer marketing", trend: 60 },
  ],
  "customer service manager": [
    { skill: "customer service", trend: 98 },
    { skill: "conflict resolution", trend: 96 },
    { skill: "team leadership", trend: 94 },
    { skill: "crm", trend: 90 },
    { skill: "communication", trend: 88 },
    { skill: "problem solving", trend: 85 },
    { skill: "customer satisfaction", trend: 82 },
    { skill: "call center management", trend: 78 },
    { skill: "quality assurance", trend: 75 },
    { skill: "training", trend: 70 },
    { skill: "data analysis", trend: 65 },
    { skill: "process improvement", trend: 60 },
  ],
  "real estate agent": [
    { skill: "negotiation", trend: 98 },
    { skill: "property valuation", trend: 96 },
    { skill: "market analysis", trend: 94 },
    { skill: "client relations", trend: 90 },
    { skill: "contract management", trend: 88 },
    { skill: "marketing", trend: 85 },
    { skill: "crm", trend: 82 },
    { skill: "property management", trend: 78 },
    { skill: "sales", trend: 75 },
    { skill: "networking", trend: 70 },
    { skill: "communication", trend: 65 },
    { skill: "legal compliance", trend: 60 },
  ],
  "photographer": [
    { skill: "adobe lightroom", trend: 98 },
    { skill: "adobe photoshop", trend: 96 },
    { skill: "photography", trend: 94 },
    { skill: "photo editing", trend: 90 },
    { skill: "studio lighting", trend: 88 },
    { skill: "composition", trend: 85 },
    { skill: "portrait photography", trend: 82 },
    { skill: "event photography", trend: 78 },
    { skill: "video editing", trend: 75 },
    { skill: "drone photography", trend: 70 },
    { skill: "color correction", trend: 65 },
    { skill: "client management", trend: 60 },
  ],
  "video editor": [
    { skill: "adobe premiere pro", trend: 98 },
    { skill: "after effects", trend: 96 },
    { skill: "final cut pro", trend: 94 },
    { skill: "color grading", trend: 90 },
    { skill: "motion graphics", trend: 88 },
    { skill: "sound editing", trend: 85 },
    { skill: "storytelling", trend: 82 },
    { skill: "davinci resolve", trend: 78 },
    { skill: "video production", trend: 75 },
    { skill: "youtube", trend: 70 },
    { skill: "social media video", trend: 65 },
    { skill: "animation", trend: 60 },
  ],
  // HEALTHCARE & MEDICAL
  "nurse": [
    { skill: "patient care", trend: 98 },
    { skill: "vital signs monitoring", trend: 96 },
    { skill: "medication administration", trend: 94 },
    { skill: "electronic health records", trend: 90 },
    { skill: "wound care", trend: 88 },
    { skill: "infection control", trend: 85 },
    { skill: "cpr certification", trend: 82 },
    { skill: "iv therapy", trend: 78 },
    { skill: "patient education", trend: 75 },
    { skill: "emergency response", trend: 70 },
    { skill: "medical terminology", trend: 65 },
    { skill: "compassionate care", trend: 60 },
  ],
  "doctor": [
    { skill: "patient diagnosis", trend: 98 },
    { skill: "clinical examination", trend: 96 },
    { skill: "treatment planning", trend: 94 },
    { skill: "medical imaging", trend: 90 },
    { skill: "pharmacology", trend: 88 },
    { skill: "surgical procedures", trend: 85 },
    { skill: "electronic health records", trend: 82 },
    { skill: "patient communication", trend: 78 },
    { skill: "emergency medicine", trend: 75 },
    { skill: "medical research", trend: 70 },
    { skill: "evidence-based medicine", trend: 65 },
    { skill: "medical ethics", trend: 60 },
  ],
  "pharmacist": [
    { skill: "pharmacology", trend: 98 },
    { skill: "prescription dispensing", trend: 96 },
    { skill: "drug interactions", trend: 94 },
    { skill: "patient counseling", trend: 90 },
    { skill: "pharmacy management", trend: 88 },
    { skill: "immunizations", trend: 85 },
    { skill: "clinical pharmacy", trend: 82 },
    { skill: "medication therapy management", trend: 78 },
    { skill: "pharmaceutical calculations", trend: 75 },
    { skill: "regulatory compliance", trend: 70 },
    { skill: "inventory management", trend: 65 },
    { skill: "patient safety", trend: 60 },
  ],
  "medical technician": [
    { skill: "laboratory testing", trend: 98 },
    { skill: "phlebotomy", trend: 96 },
    { skill: "specimen analysis", trend: 94 },
    { skill: "medical equipment operation", trend: 90 },
    { skill: "quality control", trend: 88 },
    { skill: "laboratory safety", trend: 85 },
    { skill: "data entry", trend: 82 },
    { skill: "microscopy", trend: 78 },
    { skill: "patient preparation", trend: 75 },
    { skill: "medical terminology", trend: 70 },
    { skill: "report writing", trend: 65 },
    { skill: "attention to detail", trend: 60 },
  ],
  "physiotherapist": [
    { skill: "patient assessment", trend: 98 },
    { skill: "rehabilitation planning", trend: 96 },
    { skill: "exercise prescription", trend: 94 },
    { skill: "manual therapy", trend: 90 },
    { skill: "pain management", trend: 88 },
    { skill: "musculoskeletal treatment", trend: 85 },
    { skill: "patient education", trend: 82 },
    { skill: "sports injury treatment", trend: 78 },
    { skill: "neurological rehabilitation", trend: 75 },
    { skill: "therapeutic exercises", trend: 70 },
    { skill: "electrotherapy", trend: 65 },
    { skill: "documentation", trend: 60 },
  ],
  "dentist": [
    { skill: "oral examination", trend: 98 },
    { skill: "dental procedures", trend: 96 },
    { skill: "oral surgery", trend: 94 },
    { skill: "x-ray interpretation", trend: 90 },
    { skill: "patient care", trend: 88 },
    { skill: "dental hygiene", trend: 85 },
    { skill: "cosmetic dentistry", trend: 82 },
    { skill: "endodontics", trend: 78 },
    { skill: "orthodontics", trend: 75 },
    { skill: "dental imaging", trend: 70 },
    { skill: "infection control", trend: 65 },
    { skill: "patient communication", trend: 60 },
  ],
  // EDUCATION & TRAINING
  "teacher": [
    { skill: "lesson planning", trend: 98 },
    { skill: "classroom management", trend: 96 },
    { skill: "student assessment", trend: 94 },
    { skill: "curriculum development", trend: 90 },
    { skill: "educational technology", trend: 88 },
    { skill: "differentiated instruction", trend: 85 },
    { skill: "parent communication", trend: 82 },
    { skill: "special education", trend: 78 },
    { skill: "behavior management", trend: 75 },
    { skill: "online teaching", trend: 70 },
    { skill: "google classroom", trend: 65 },
    { skill: "student engagement", trend: 60 },
  ],
  "professor": [
    { skill: "research", trend: 98 },
    { skill: "academic writing", trend: 96 },
    { skill: "lecturing", trend: 94 },
    { skill: "curriculum design", trend: 90 },
    { skill: "student mentoring", trend: 88 },
    { skill: "publication", trend: 85 },
    { skill: "grant writing", trend: 82 },
    { skill: "peer review", trend: 78 },
    { skill: "data analysis", trend: 75 },
    { skill: "conference presentation", trend: 70 },
    { skill: "academic advising", trend: 65 },
    { skill: "online teaching", trend: 60 },
  ],
  "corporate trainer": [
    { skill: "training delivery", trend: 98 },
    { skill: "instructional design", trend: 96 },
    { skill: "needs assessment", trend: 94 },
    { skill: "presentation skills", trend: 90 },
    { skill: "e-learning development", trend: 88 },
    { skill: "facilitation", trend: 85 },
    { skill: "training evaluation", trend: 82 },
    { skill: "adult learning theory", trend: 78 },
    { skill: "learning management systems", trend: 75 },
    { skill: "coaching", trend: 70 },
    { skill: "curriculum development", trend: 65 },
    { skill: "communication", trend: 60 },
  ],
  // HOSPITALITY & TOURISM
  "hotel manager": [
    { skill: "hospitality management", trend: 98 },
    { skill: "guest relations", trend: 96 },
    { skill: "operations management", trend: 94 },
    { skill: "revenue management", trend: 90 },
    { skill: "staff supervision", trend: 88 },
    { skill: "customer service", trend: 85 },
    { skill: "budget management", trend: 82 },
    { skill: "event planning", trend: 78 },
    { skill: "food and beverage management", trend: 75 },
    { skill: "property management systems", trend: 70 },
    { skill: "quality assurance", trend: 65 },
    { skill: "conflict resolution", trend: 60 },
  ],
  "chef": [
    { skill: "culinary arts", trend: 98 },
    { skill: "menu planning", trend: 96 },
    { skill: "food preparation", trend: 94 },
    { skill: "kitchen management", trend: 90 },
    { skill: "food safety", trend: 88 },
    { skill: "recipe development", trend: 85 },
    { skill: "inventory management", trend: 82 },
    { skill: "cooking techniques", trend: 78 },
    { skill: "plating and presentation", trend: 75 },
    { skill: "nutrition knowledge", trend: 70 },
    { skill: "cost control", trend: 65 },
    { skill: "team leadership", trend: 60 },
  ],
  "tour guide": [
    { skill: "tourism knowledge", trend: 98 },
    { skill: "public speaking", trend: 96 },
    { skill: "customer service", trend: 94 },
    { skill: "historical knowledge", trend: 90 },
    { skill: "language skills", trend: 88 },
    { skill: "time management", trend: 85 },
    { skill: "group management", trend: 82 },
    { skill: "first aid", trend: 78 },
    { skill: "storytelling", trend: 75 },
    { skill: "cultural awareness", trend: 70 },
    { skill: "navigation", trend: 65 },
    { skill: "problem solving", trend: 60 },
  ],
  "flight attendant": [
    { skill: "passenger safety", trend: 98 },
    { skill: "customer service", trend: 96 },
    { skill: "emergency procedures", trend: 94 },
    { skill: "first aid", trend: 90 },
    { skill: "communication", trend: 88 },
    { skill: "conflict resolution", trend: 85 },
    { skill: "cultural sensitivity", trend: 82 },
    { skill: "time management", trend: 78 },
    { skill: "multilingual", trend: 75 },
    { skill: "teamwork", trend: 70 },
    { skill: "service excellence", trend: 65 },
    { skill: "attention to detail", trend: 60 },
  ],
  // LEGAL & LAW ENFORCEMENT
  "lawyer": [
    { skill: "legal research", trend: 98 },
    { skill: "case preparation", trend: 96 },
    { skill: "contract drafting", trend: 94 },
    { skill: "negotiation", trend: 90 },
    { skill: "litigation", trend: 88 },
    { skill: "legal writing", trend: 85 },
    { skill: "client consultation", trend: 82 },
    { skill: "court representation", trend: 78 },
    { skill: "regulatory compliance", trend: 75 },
    { skill: "document review", trend: 70 },
    { skill: "analytical thinking", trend: 65 },
    { skill: "communication", trend: 60 },
  ],
  "paralegal": [
    { skill: "legal research", trend: 98 },
    { skill: "document preparation", trend: 96 },
    { skill: "case management", trend: 94 },
    { skill: "legal writing", trend: 90 },
    { skill: "file organization", trend: 88 },
    { skill: "client communication", trend: 85 },
    { skill: "court filing", trend: 82 },
    { skill: "contract review", trend: 78 },
    { skill: "legal terminology", trend: 75 },
    { skill: "attention to detail", trend: 70 },
    { skill: "time management", trend: 65 },
    { skill: "microsoft office", trend: 60 },
  ],
  "police officer": [
    { skill: "law enforcement", trend: 98 },
    { skill: "criminal investigation", trend: 96 },
    { skill: "community policing", trend: 94 },
    { skill: "report writing", trend: 90 },
    { skill: "conflict resolution", trend: 88 },
    { skill: "emergency response", trend: 85 },
    { skill: "evidence collection", trend: 82 },
    { skill: "traffic control", trend: 78 },
    { skill: "firearms training", trend: 75 },
    { skill: "first aid", trend: 70 },
    { skill: "physical fitness", trend: 65 },
    { skill: "communication", trend: 60 },
  ],
  // AGRICULTURE & ENVIRONMENT
  "agricultural scientist": [
    { skill: "crop management", trend: 98 },
    { skill: "soil science", trend: 96 },
    { skill: "data analysis", trend: 94 },
    { skill: "research methods", trend: 90 },
    { skill: "sustainable farming", trend: 88 },
    { skill: "pest management", trend: 85 },
    { skill: "irrigation systems", trend: 82 },
    { skill: "genetics", trend: 78 },
    { skill: "gis mapping", trend: 75 },
    { skill: "climate adaptation", trend: 70 },
    { skill: "agricultural economics", trend: 65 },
    { skill: "field trials", trend: 60 },
  ],
  "environmental engineer": [
    { skill: "environmental assessment", trend: 98 },
    { skill: "waste management", trend: 96 },
    { skill: "water treatment", trend: 94 },
    { skill: "air quality control", trend: 90 },
    { skill: "environmental regulations", trend: 88 },
    { skill: "sustainability", trend: 85 },
    { skill: "remediation", trend: 82 },
    { skill: "data analysis", trend: 78 },
    { skill: "gis", trend: 75 },
    { skill: "environmental modeling", trend: 70 },
    { skill: "report writing", trend: 65 },
    { skill: "project management", trend: 60 },
  ],
  "farmer": [
    { skill: "crop cultivation", trend: 98 },
    { skill: "livestock management", trend: 96 },
    { skill: "soil management", trend: 94 },
    { skill: "irrigation", trend: 90 },
    { skill: "equipment operation", trend: 88 },
    { skill: "pest control", trend: 85 },
    { skill: "harvesting", trend: 82 },
    { skill: "farm planning", trend: 78 },
    { skill: "weather monitoring", trend: 75 },
    { skill: "record keeping", trend: 70 },
    { skill: "sustainable practices", trend: 65 },
    { skill: "market analysis", trend: 60 },
  ],
  // TRANSPORTATION & LOGISTICS
  "truck driver": [
    { skill: "commercial driving", trend: 98 },
    { skill: "route planning", trend: 96 },
    { skill: "vehicle maintenance", trend: 94 },
    { skill: "safety regulations", trend: 90 },
    { skill: "navigation", trend: 88 },
    { skill: "log management", trend: 85 },
    { skill: "cargo handling", trend: 82 },
    { skill: "time management", trend: 78 },
    { skill: "defensive driving", trend: 75 },
    { skill: "gps systems", trend: 70 },
    { skill: "customer service", trend: 65 },
    { skill: "fuel efficiency", trend: 60 },
  ],
  "logistics coordinator": [
    { skill: "supply chain management", trend: 98 },
    { skill: "inventory control", trend: 96 },
    { skill: "warehouse management", trend: 94 },
    { skill: "transportation planning", trend: 90 },
    { skill: "erp systems", trend: 88 },
    { skill: "vendor management", trend: 85 },
    { skill: "data analysis", trend: 82 },
    { skill: "shipping regulations", trend: 78 },
    { skill: "problem solving", trend: 75 },
    { skill: "communication", trend: 70 },
    { skill: "cost optimization", trend: 65 },
    { skill: "excel", trend: 60 },
  ],
  "pilot": [
    { skill: "flight operations", trend: 98 },
    { skill: "navigation", trend: 96 },
    { skill: "aviation regulations", trend: 94 },
    { skill: "aircraft systems", trend: 90 },
    { skill: "weather analysis", trend: 88 },
    { skill: "emergency procedures", trend: 85 },
    { skill: "flight planning", trend: 82 },
    { skill: "communication", trend: 78 },
    { skill: "instrument flying", trend: 75 },
    { skill: "crew resource management", trend: 70 },
    { skill: "decision making", trend: 65 },
    { skill: "situational awareness", trend: 60 },
  ],
  // CREATIVE & ARTS
  "graphic designer": [
    { skill: "adobe photoshop", trend: 98 },
    { skill: "adobe illustrator", trend: 96 },
    { skill: "figma", trend: 94 },
    { skill: "branding", trend: 90 },
    { skill: "typography", trend: 88 },
    { skill: "ui design", trend: 85 },
    { skill: "color theory", trend: 82 },
    { skill: "layout design", trend: 78 },
    { skill: "print design", trend: 75 },
    { skill: "motion graphics", trend: 70 },
    { skill: "creative thinking", trend: 65 },
    { skill: "client communication", trend: 60 },
  ],
  "musician": [
    { skill: "music theory", trend: 98 },
    { skill: "instrument proficiency", trend: 96 },
    { skill: "music production", trend: 94 },
    { skill: "audio editing", trend: 90 },
    { skill: "composition", trend: 88 },
    { skill: "performance", trend: 85 },
    { skill: "recording techniques", trend: 82 },
    { skill: "sound mixing", trend: 78 },
    { skill: "music software", trend: 75 },
    { skill: "improvisation", trend: 70 },
    { skill: "collaboration", trend: 65 },
    { skill: "marketing", trend: 60 },
  ],
  "actor": [
    { skill: "acting techniques", trend: 98 },
    { skill: "script analysis", trend: 96 },
    { skill: "voice modulation", trend: 94 },
    { skill: "improvisation", trend: 90 },
    { skill: "stage presence", trend: 88 },
    { skill: "character development", trend: 85 },
    { skill: "emotional expression", trend: 82 },
    { skill: "movement", trend: 78 },
    { skill: "memorization", trend: 75 },
    { skill: "audition preparation", trend: 70 },
    { skill: "collaboration", trend: 65 },
    { skill: "networking", trend: 60 },
  ],
  "interior designer": [
    { skill: "space planning", trend: 98 },
    { skill: "autocad", trend: 96 },
    { skill: "3d modeling", trend: 94 },
    { skill: "color theory", trend: 90 },
    { skill: "furniture selection", trend: 88 },
    { skill: "sketchup", trend: 85 },
    { skill: "lighting design", trend: 82 },
    { skill: "material selection", trend: 78 },
    { skill: "client consultation", trend: 75 },
    { skill: "budget management", trend: 70 },
    { skill: "project management", trend: 65 },
    { skill: "sustainable design", trend: 60 },
  ],
  "fashion designer": [
    { skill: "fashion illustration", trend: 98 },
    { skill: "pattern making", trend: 96 },
    { skill: "sewing", trend: 94 },
    { skill: "textile knowledge", trend: 90 },
    { skill: "trend forecasting", trend: 88 },
    { skill: "draping", trend: 85 },
    { skill: "adobe illustrator", trend: 82 },
    { skill: "garment construction", trend: 78 },
    { skill: "color theory", trend: 75 },
    { skill: "fashion marketing", trend: 70 },
    { skill: "merchandising", trend: 65 },
    { skill: "portfolio development", trend: 60 },
  ],
  // SPORTS & FITNESS
  "fitness trainer": [
    { skill: "exercise programming", trend: 98 },
    { skill: "nutrition counseling", trend: 96 },
    { skill: "strength training", trend: 94 },
    { skill: "client assessment", trend: 90 },
    { skill: "cpr certification", trend: 88 },
    { skill: "cardiovascular training", trend: 85 },
    { skill: "flexibility training", trend: 82 },
    { skill: "weight management", trend: 78 },
    { skill: "motivation", trend: 75 },
    { skill: "injury prevention", trend: 70 },
    { skill: "group fitness", trend: 65 },
    { skill: "anatomy", trend: 60 },
  ],
  "sports coach": [
    { skill: "athlete development", trend: 98 },
    { skill: "game strategy", trend: 96 },
    { skill: "performance analysis", trend: 94 },
    { skill: "team management", trend: 90 },
    { skill: "communication", trend: 88 },
    { skill: "motivation", trend: 85 },
    { skill: "sports psychology", trend: 82 },
    { skill: "fitness training", trend: 78 },
    { skill: "injury management", trend: 75 },
    { skill: "video analysis", trend: 70 },
    { skill: "leadership", trend: 65 },
    { skill: "planning", trend: 60 },
  ],
  "yoga instructor": [
    { skill: "yoga asanas", trend: 98 },
    { skill: "meditation", trend: 96 },
    { skill: "breathing techniques", trend: 94 },
    { skill: "anatomy", trend: 90 },
    { skill: "philosophy", trend: 88 },
    { skill: "class sequencing", trend: 85 },
    { skill: "student adjustment", trend: 82 },
    { skill: "mindfulness", trend: 78 },
    { skill: "stress management", trend: 75 },
    { skill: "communication", trend: 70 },
    { skill: "nutrition", trend: 65 },
    { skill: "injury prevention", trend: 60 },
  ],
  // SOCIAL SERVICES
  "social worker": [
    { skill: "case management", trend: 98 },
    { skill: "counseling", trend: 96 },
    { skill: "crisis intervention", trend: 94 },
    { skill: "client advocacy", trend: 90 },
    { skill: "assessment", trend: 88 },
    { skill: "community resources", trend: 85 },
    { skill: "documentation", trend: 82 },
    { skill: "empathy", trend: 78 },
    { skill: "communication", trend: 75 },
    { skill: "cultural competence", trend: 70 },
    { skill: "boundary setting", trend: 65 },
    { skill: "problem solving", trend: 60 },
  ],
  "psychologist": [
    { skill: "psychological assessment", trend: 98 },
    { skill: "therapy techniques", trend: 96 },
    { skill: "cognitive behavioral therapy", trend: 94 },
    { skill: "counseling", trend: 90 },
    { skill: "research methods", trend: 88 },
    { skill: "diagnosis", trend: 85 },
    { skill: "treatment planning", trend: 82 },
    { skill: "crisis intervention", trend: 78 },
    { skill: "report writing", trend: 75 },
    { skill: "empathy", trend: 70 },
    { skill: "active listening", trend: 65 },
    { skill: "ethics", trend: 60 },
  ],
  "counselor": [
    { skill: "active listening", trend: 98 },
    { skill: "empathy", trend: 96 },
    { skill: "crisis intervention", trend: 94 },
    { skill: "treatment planning", trend: 90 },
    { skill: "group therapy", trend: 88 },
    { skill: "mental health assessment", trend: 85 },
    { skill: "communication", trend: 82 },
    { skill: "confidentiality", trend: 78 },
    { skill: "boundary setting", trend: 75 },
    { skill: "documentation", trend: 70 },
    { skill: "stress management", trend: 65 },
    { skill: "client advocacy", trend: 60 },
  ],
  // REAL ESTATE & PROPERTY
  "real estate agent": [
    { skill: "property marketing", trend: 98 },
    { skill: "negotiation", trend: 96 },
    { skill: "client relations", trend: 94 },
    { skill: "market analysis", trend: 90 },
    { skill: "contract management", trend: 88 },
    { skill: "property valuation", trend: 85 },
    { skill: "lead generation", trend: 82 },
    { skill: "communication", trend: 78 },
    { skill: "social media marketing", trend: 75 },
    { skill: "networking", trend: 70 },
    { skill: "crm systems", trend: 65 },
    { skill: "legal compliance", trend: 60 },
  ],
  "property manager": [
    { skill: "property maintenance", trend: 98 },
    { skill: "tenant relations", trend: 96 },
    { skill: "lease management", trend: 94 },
    { skill: "budget management", trend: 90 },
    { skill: "vendor management", trend: 88 },
    { skill: "property inspections", trend: 85 },
    { skill: "rent collection", trend: 82 },
    { skill: "legal compliance", trend: 78 },
    { skill: "conflict resolution", trend: 75 },
    { skill: "accounting", trend: 70 },
    { skill: "marketing", trend: 65 },
    { skill: "organization", trend: 60 },
  ],
  "architect": [
    { skill: "autocad", trend: 98 },
    { skill: "revit", trend: 96 },
    { skill: "architectural design", trend: 94 },
    { skill: "3d modeling", trend: 90 },
    { skill: "building codes", trend: 88 },
    { skill: "sustainable design", trend: 85 },
    { skill: "project management", trend: 82 },
    { skill: "sketchup", trend: 78 },
    { skill: "client consultation", trend: 75 },
    { skill: "construction documents", trend: 70 },
    { skill: "site analysis", trend: 65 },
    { skill: "presentation skills", trend: 60 },
  ],
  // MANUFACTURING & PRODUCTION
  "mechanical engineer": [
    { skill: "cad", trend: 98 },
    { skill: "solidworks", trend: 96 },
    { skill: "autocad", trend: 94 },
    { skill: "thermodynamics", trend: 90 },
    { skill: "manufacturing processes", trend: 88 },
    { skill: "finite element analysis", trend: 85 },
    { skill: "matlab", trend: 82 },
    { skill: "mechanical design", trend: 78 },
    { skill: "quality control", trend: 75 },
    { skill: "project management", trend: 70 },
    { skill: "hvac", trend: 65 },
    { skill: "lean manufacturing", trend: 60 },
  ],
  "electrical engineer": [
    { skill: "circuit design", trend: 98 },
    { skill: "autocad electrical", trend: 96 },
    { skill: "plc programming", trend: 94 },
    { skill: "power systems", trend: 90 },
    { skill: "electronics", trend: 88 },
    { skill: "control systems", trend: 85 },
    { skill: "matlab", trend: 82 },
    { skill: "pcb design", trend: 78 },
    { skill: "testing", trend: 75 },
    { skill: "project management", trend: 70 },
    { skill: "troubleshooting", trend: 65 },
    { skill: "safety standards", trend: 60 },
  ],
  "quality assurance inspector": [
    { skill: "quality control", trend: 98 },
    { skill: "inspection techniques", trend: 96 },
    { skill: "iso standards", trend: 94 },
    { skill: "documentation", trend: 90 },
    { skill: "statistical analysis", trend: 88 },
    { skill: "defect tracking", trend: 85 },
    { skill: "measurement tools", trend: 82 },
    { skill: "report writing", trend: 78 },
    { skill: "process improvement", trend: 75 },
    { skill: "attention to detail", trend: 70 },
    { skill: "problem solving", trend: 65 },
    { skill: "teamwork", trend: 60 },
  ],
  "production manager": [
    { skill: "production planning", trend: 98 },
    { skill: "lean manufacturing", trend: 96 },
    { skill: "quality control", trend: 94 },
    { skill: "team leadership", trend: 90 },
    { skill: "process optimization", trend: 88 },
    { skill: "inventory management", trend: 85 },
    { skill: "safety management", trend: 82 },
    { skill: "budget management", trend: 78 },
    { skill: "scheduling", trend: 75 },
    { skill: "continuous improvement", trend: 70 },
    { skill: "problem solving", trend: 65 },
    { skill: "communication", trend: 60 },
  ],
  // ENERGY & UTILITIES
  "electrical technician": [
    { skill: "electrical systems", trend: 98 },
    { skill: "wiring", trend: 96 },
    { skill: "troubleshooting", trend: 94 },
    { skill: "blueprint reading", trend: 90 },
    { skill: "safety procedures", trend: 88 },
    { skill: "preventive maintenance", trend: 85 },
    { skill: "multimeter usage", trend: 82 },
    { skill: "circuit analysis", trend: 78 },
    { skill: "tool proficiency", trend: 75 },
    { skill: "documentation", trend: 70 },
    { skill: "time management", trend: 65 },
    { skill: "communication", trend: 60 },
  ],
  "solar energy technician": [
    { skill: "solar panel installation", trend: 98 },
    { skill: "electrical systems", trend: 96 },
    { skill: "system maintenance", trend: 94 },
    { skill: "troubleshooting", trend: 90 },
    { skill: "safety protocols", trend: 88 },
    { skill: "photovoltaic systems", trend: 85 },
    { skill: "battery storage", trend: 82 },
    { skill: "energy efficiency", trend: 78 },
    { skill: "blueprint reading", trend: 75 },
    { skill: "hand tools", trend: 70 },
    { skill: "customer service", trend: 65 },
    { skill: "documentation", trend: 60 },
  ],
  // CONSTRUCTION & TRADES
  "construction manager": [
    { skill: "project management", trend: 98 },
    { skill: "construction planning", trend: 96 },
    { skill: "budget management", trend: 94 },
    { skill: "safety management", trend: 90 },
    { skill: "contract management", trend: 88 },
    { skill: "scheduling", trend: 85 },
    { skill: "team leadership", trend: 82 },
    { skill: "quality control", trend: 78 },
    { skill: "blueprint reading", trend: 75 },
    { skill: "communication", trend: 70 },
    { skill: "problem solving", trend: 65 },
    { skill: "regulatory compliance", trend: 60 },
  ],
  "electrician": [
    { skill: "electrical wiring", trend: 98 },
    { skill: "troubleshooting", trend: 96 },
    { skill: "blueprint reading", trend: 94 },
    { skill: "safety procedures", trend: 90 },
    { skill: "circuit installation", trend: 88 },
    { skill: "code compliance", trend: 85 },
    { skill: "preventive maintenance", trend: 82 },
    { skill: "hand tools", trend: 78 },
    { skill: "power distribution", trend: 75 },
    { skill: "customer service", trend: 70 },
    { skill: "time management", trend: 65 },
    { skill: "documentation", trend: 60 },
  ],
  "plumber": [
    { skill: "pipe installation", trend: 98 },
    { skill: "troubleshooting", trend: 96 },
    { skill: "blueprint reading", trend: 94 },
    { skill: "fixture repair", trend: 90 },
    { skill: "drainage systems", trend: 88 },
    { skill: "water supply systems", trend: 85 },
    { skill: "safety procedures", trend: 82 },
    { skill: "tool proficiency", trend: 78 },
    { skill: "customer service", trend: 75 },
    { skill: "code compliance", trend: 70 },
    { skill: "time management", trend: 65 },
    { skill: "problem solving", trend: 60 },
  ],
  "carpenter": [
    { skill: "woodworking", trend: 98 },
    { skill: "blueprint reading", trend: 96 },
    { skill: "measurement", trend: 94 },
    { skill: "power tools", trend: 90 },
    { skill: "framing", trend: 88 },
    { skill: "finish carpentry", trend: 85 },
    { skill: "cabinet making", trend: 82 },
    { skill: "safety procedures", trend: 78 },
    { skill: "material selection", trend: 75 },
    { skill: "attention to detail", trend: 70 },
    { skill: "problem solving", trend: 65 },
    { skill: "time management", trend: 60 },
  ],
};

function getTrendColor(trend) {
  if (trend >= 85) return "#16a34a";
  if (trend >= 65) return "#0f52ba";
  if (trend >= 45) return "#d97706";
  return "#9ca3af";
}

function getTrendLabel(trend) {
  if (trend >= 85) return "🔥 Hot";
  if (trend >= 65) return "📈 Rising";
  if (trend >= 45) return "➡️ Stable";
  return "📉 Declining";
}

function resolveRole(desiredRole = "") {
  const normalized = desiredRole.toLowerCase();
  return Object.keys(TRENDING_SKILLS).find((role) =>
    normalized.includes(role)
  ) || null;
}

export default function ScoreCard({ score, formData, profileType, scoreBreakdown, strongPoints }) {
  // Dynamic score color
  const getScoreColor = (score) => {
    if (score <= 40) return "#dc2626";
    if (score <= 65) return "#d97706";
    if (score <= 80) return "#1a56db";
    return "#16a34a";
  };

  const scoreColor = getScoreColor(score);
  const scoreTone =
    score >= 80 ? "excellent" : score >= 65 ? "strong" : "improving";

  const isExperienced = profileType === "experienced";
  const scoreLabel = isExperienced ? "Experienced Profile ATS Score" : "Resume score";

  const roleKey = formData?.desiredJobRoles
    ? resolveRole(formData.desiredJobRoles)
    : null;

  const trendingSkills = roleKey ? TRENDING_SKILLS[roleKey] : null;

  const userSkills = (formData?.skills || []).map((s) =>
    s.toLowerCase().trim()
  );

  const matchedSkills = trendingSkills
    ? trendingSkills.filter((ts) =>
        userSkills.some(
          (us) =>
            us === ts.skill ||
            us.includes(ts.skill) ||
            ts.skill.includes(us)
        )
      )
    : [];

  const missingSkills = trendingSkills
    ? trendingSkills.filter(
        (ts) =>
          !userSkills.some(
            (us) =>
              us === ts.skill ||
              us.includes(ts.skill) ||
              ts.skill.includes(us)
          )
      )
    : [];

  return (
    <div className={`dashboard-panel dashboard-score-card ${scoreTone}`}
      style={{ display: "flex", flexDirection: "column", gap: "24px" }}>

      {/* Score Section */}
      <div style={{ display: "flex", flexWrap: "wrap", gap: "24px", alignItems: "center" }}>
        <div style={{ flex: 1, minWidth: "200px" }}>
          <span className="dashboard-section-label">{scoreLabel}</span>
          <h2>{isExperienced ? "Your experienced profile strength" : "Your current resume strength"}</h2>
          <p>{isExperienced 
            ? "This score reflects how well your experience, skills, and background align with ATS systems for experienced professionals."
            : "This score reflects how complete and compelling your resume looks based on the details you submitted."}</p>
        </div>
        <div className="dashboard-score-meter">
          <div className="dashboard-score-ring">
            <strong>{score}</strong>
            <span>/ 100</span>
          </div>
          <div className="dashboard-score-summary">
            <div>
              <span>Status</span>
              <strong>
                {score >= 80 ? "Excellent" : score >= 65 ? "Strong" : "Needs improvement"}
              </strong>
            </div>
            <div>
              <span>Next goal</span>
              <strong>{Math.min(100, score + 12)}+</strong>
            </div>
          </div>
        </div>
      </div>

      {/* Trending Skills Breakdown - Always Visible */}
      {trendingSkills && (
        <div style={{ borderTop: "1px solid rgba(0,0,0,0.08)", paddingTop: "20px" }}>

          {/* Header */}
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: "8px", marginBottom: "16px" }}>
            <div>
              <h3 style={{ margin: 0, fontSize: "1rem", fontWeight: 700 }}>
                📊 Trending Skills for {formData.desiredJobRoles}
              </h3>
              <p style={{ margin: "4px 0 0", fontSize: "0.82rem", color: "#6b7280" }}>
                Based on current market demand — green means high demand right now
              </p>
            </div>
            <div style={{ display: "flex", gap: "12px", flexWrap: "wrap" }}>
              <span style={{ fontSize: "0.78rem", fontWeight: 600, color: "#16a34a" }}>
                ✅ Matched: {matchedSkills.length}
              </span>
              <span style={{ fontSize: "0.78rem", fontWeight: 600, color: "#b42318" }}>
                ❌ Missing: {missingSkills.length}
              </span>
            </div>
          </div>

          {/* Skills List */}
          <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
            {trendingSkills.map(({ skill, trend }) => {
              const isMatched = userSkills.some(
                (us) =>
                  us === skill ||
                  us.includes(skill) ||
                  skill.includes(us)
              );
              const color = getTrendColor(trend);
              const label = getTrendLabel(trend);

              return (
                <div key={skill}>
                  <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "4px" }}>
                    <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                      <span style={{ fontSize: "13px", fontWeight: 600, textTransform: "capitalize" }}>
                        {skill}
                      </span>
                      {isMatched && (
                        <span style={{ fontSize: "11px", background: "#dcfce7", color: "#16a34a", borderRadius: "999px", padding: "1px 8px", fontWeight: 700 }}>
                          ✓ You have this
                        </span>
                      )}
                    </div>
                    <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                      <span style={{ fontSize: "11px", color: color, fontWeight: 600 }}>{label}</span>
                      <span style={{ fontSize: "12px", color: "#6b7280", fontWeight: 600 }}>{trend}%</span>
                    </div>
                  </div>

                  {/* Progress Bar */}
                  <div style={{ height: "8px", background: "#f3f4f6", borderRadius: "999px", overflow: "hidden" }}>
                    <div style={{
                      height: "100%",
                      width: `${trend}%`,
                      background: isMatched
                        ? `linear-gradient(90deg, ${color}, ${color}cc)`
                        : `linear-gradient(90deg, #e5e7eb, #d1d5db)`,
                      borderRadius: "999px",
                      transition: "width 0.8s ease",
                      opacity: isMatched ? 1 : 0.5,
                    }} />
                  </div>
                </div>
              );
            })}
          </div>

          {/* Missing Skills Tip */}
          {missingSkills.length > 0 && (
            <div style={{ marginTop: "16px", padding: "12px", background: "#fef9ec", borderRadius: "10px", border: "1px solid #fde68a" }}>
              <p style={{ margin: 0, fontSize: "0.82rem", color: "#92400e", fontWeight: 600 }}>
                💡 Top missing skills to add:&nbsp;
                <span style={{ fontWeight: 400 }}>
                  {missingSkills.slice(0, 4).map(s => s.skill).join(", ")}
                </span>
              </p>
            </div>
          )}
        </div>
      )}
    </div>
  );
}